branches:
  except:
    - gh-pages
language: C
complier:
  - gcc
before_install:
  - sudo apt-get install aspell-es 
script: OUTPUT=`cat README.md | aspell list -d es -p ./.aspell.es.pws`; if [ -n "$OUTPUT" ]; then exit 1; fi
